apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-credentials
  namespace: default
type: Opaque
stringData:
  # Replace these with your actual credentials
  accountKey: "your-account-key-here"
  connectionString: "DefaultEndpointsProtocol=https;AccountName=yourstorageaccount;AccountKey=your-account-key-here;EndpointSuffix=core.windows.net"
  # Or alternatively use SAS token
  # sasToken: "?sv=2020-08-04&ss=bf&srt=sco&sp=rwdlacitfx&se=2023-12-31T00:00:00Z&st=2023-01-01T00:00:00Z&spr=https&sig=abcdefghijklmnopqrstuvwxyz"
